# Generated by Django 3.0.6 on 2020-05-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_auto_20200520_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(max_length=20, verbose_name='RG'),
        ),
    ]
