# Generated by Django 3.0.6 on 2020-05-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_auto_20200521_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='naturalidade',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(max_length=20, verbose_name='RG SSP'),
        ),
    ]
