# Generated by Django 3.0.5 on 2020-04-28 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0003_auto_20200425_1135'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Modificado em')),
                ('num_doc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Documento')),
                ('movimento', models.CharField(choices=[('r', 'realizar'), ('p', 'pagar')], max_length=1)),
                ('funcionário', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='EmprestimoItens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_emprestado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Emprestado')),
                ('juros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Juros')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.Emprestimo')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
