# Generated by Django 3.0.5 on 2020-04-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='funcionário',
            new_name='funcionario',
        ),
    ]
