# Generated by Django 3.0.5 on 2020-04-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0003_auto_20200428_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimoitens',
            name='emprestimo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='emprestimo.Emprestimo'),
        ),
    ]
