# Generated by Django 3.0.5 on 2020-04-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0005_auto_20200429_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimoitens',
            name='valor_prestacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da prestação'),
        ),
    ]
