# Generated by Django 3.0.5 on 2020-04-30 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20200425_1135'),
        ('emprestimo', '0006_emprestimoitens_valor_prestacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='movimento',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='qtd_parcelas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtd Parcelas'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='valor_emprestado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Emprestado'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='valor_prestacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da prestação'),
        ),
        migrations.DeleteModel(
            name='EmprestimoItens',
        ),
    ]
