# Generated by Django 3.0.7 on 2020-10-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0025_remove_emprestimo_num_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_emprestimo_antiga',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Empréstimo antiga'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Data do Empréstimo'),
        ),
    ]
