# Generated by Django 3.0.7 on 2020-09-15 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_delete_dados_bancarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiador_nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('fiador_cpf', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF')),
                ('fiador_rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('fiador_orgao_emissor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Orgão Emissor')),
                ('fiador_nacionalidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nacionalidade')),
                ('fiador_estado_civil', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado Civil')),
                ('fiador_email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('fiador_contato1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato 1')),
                ('fiador_celular1', models.CharField(blank=True, max_length=17, null=True, verbose_name='celular 1')),
                ('whatsapp1', models.BooleanField(default=True, verbose_name='Whatsapp')),
                ('fiador_celular2', models.CharField(blank=True, max_length=17, null=True, verbose_name='celular 2')),
                ('whatsapp2', models.BooleanField(default=True, verbose_name='Whatsapp')),
                ('fiador_cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('fiador_rua', models.CharField(blank=True, max_length=60, null=True, verbose_name='Rua')),
                ('fiador_bairro', models.CharField(blank=True, max_length=40, null=True, verbose_name='Bairro')),
                ('fiador_cidade', models.CharField(blank=True, max_length=40, null=True, verbose_name='Cidade')),
                ('fiador_uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('fiador_numero_casa', models.CharField(blank=True, max_length=5, null=True, verbose_name='Nº ')),
                ('fiador_ponto_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ponto de Referencia')),
                ('fiador_complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('fiador_n_operacao', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº operação')),
                ('fiador_agencia', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº agência')),
                ('fiador_conta', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº conta')),
                ('banco', models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Banco')),
                ('tipo_de_conta', models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Tipo_de_conta')),
            ],
            options={
                'ordering': ('fiador_nome',),
            },
        ),
    ]
